version: "1.0"

services:
  movieapp:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=host.docker.internal
  postgres:
    image: postgres:10.14-alpine
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
