name: Docker Build, Tag and Push
run-name: builds docker image,  tag it and push to dockerhub
on: [push]
jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    steps:
      - name: Build the docker image
        run: docker build -t movies:latest .
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Tag the docker image
        run: docker tag movies:latest arimotearipo/movies_v2:latest
      - name: Push the tagged docker image to repository
        run: docker push arimotearipo/movies_v2:latest
